import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ 
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      {/* <body className={inter.className}>{children}</body> */}
      <body className={openSans.className}>
        <header>
          <h1>
            <Link className="homeLink" href="/home">GLobomantics</Link>
          </h1>
          <h2>
            <Link className="menuBarLink" href="/blog">Blog</Link>
          </h2>
          <h2>
            <Link className="menuBarLink" href="/settings">Settings</Link>
          </h2>
          <h2>
            <Link className="menuBarLink" href="/conference">Conference</Link>
          </h2>
        </header>
        {children}
      </body>
    </html>
  );
}
